# site name
prefixName: 古月林夕
siteName: aogui
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /images/avatar.jpg 
url: https://aogui.github.io/
description: Fear can hold you prisoner,Love can set you free.
cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 目前正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    歌单: {path: /music/, fa: fa-headphones },
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
#  友人帐: { path: /links/, fa: fa-link faa-shake }
#  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
#  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
#    我？: {path: /about/, fa: fa-meetup}, 
#    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
#    Lab: {path: /lab/, fa: fa-cogs },
#  } }
#  客户端: { path: /client/, fa: fa-android faa-vertical }
#  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.8/love.jpg
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.8/tianqi1.jpg
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.4/kj4.jpg
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.4/bj2.jpg
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.4/bj4.jpg
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.4/bj5.jpg
  - https://cdn.jsdelivr.net/gh/aogui/source@v1.6.4/about.jpg


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
#startdash: 
#  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
#  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
#  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 03/28/2020

#social  url, img PC端配置
social:
  github: {url: , img: /images/github.png}
  sina: {url: , img: /images/sina.png}
  wangyiyun: {url: , img: /images/wangyiyun.png}
#  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: , img: /images/email.svg}
  wechat: {url: /#, img: /images/wechat.png}
#  wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
#  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
#  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=2258314607&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
#  paypal: https://www.paypal.me/hojuncn
  alipay: 
  wechat: 
#  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/aogui/source@v1.5.6/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/aogui/source@v1.5.6
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 5162635250
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: S4tJFlDKmWam6o6BByDwCD2Y-gzGzoHsz
v_appKey: WYpvXvQfvobcs3u96rWHpUeL

